server:
  port: ${PORT:3008}
spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  datasource:
    url: jdbc:mysql://localhost/2b
  jackson:
    serialization:
      indent_output: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  main:
    banner-mode: 'off'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://issuer.example.com/

auth0:
  audience: "api"
